### ISSUE TITLE
Reading $.getJSON() in setInterval

### ISSUE THREAD

**Issue by amaseda** [ga-dc/slidey-mcshowington#1]
My setInterval has no problem reading my giphy .getJSON request when it's declared globally, but it's undefined when it's declared inside setInterval. The console error I receive is `Uncaught TypeError: Cannot read property 'data' of undefined`. If I keep the global declaration, the image is not randomized with every setInterval loop. Any advice on how to fix?

UPDATE: In the second scenario, I tried passing in `response` as an argument to `setBackground()` and it still didn't work.

Declared globally:

```
$(document).ready( function() {

  // API call
  response = $.getJSON( "http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&rating=pg&tag=funny+cat" );

  setInterval( function(){

    setBackground();

    // Fade in
    $("#background").fadeIn();

    // Fade out
    setTimeout( function(){
      $("#background").fadeOut();
    }, 4740);

  }, 5000);

  function setBackground() {
    $("#background").css({
      "background-image" : "url(" + response.responseJSON.data.image_url + ")",
      "display" : "none"
    });
  }

})
```

Declared inside setInterval:

```
$(document).ready( function() {

  setInterval( function(){

    // API call
    response = $.getJSON( "http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&rating=pg&tag=funny+cat" );

    setBackground();

    // Fade in
    $("#background").fadeIn();

    // Fade out
    setTimeout( function(){
      $("#background").fadeOut();
    }, 4740);

  }, 5000);

  function setBackground() {
    $("#background").css({
      "background-image" : "url(" + response.responseJSON.data.image_url + ")",
      "display" : "none"
    });
  }

})
```

**Comment by RobertAKARobin** [comment]
`$.getJSON` is asynchronous, which means it tells your browser to keep doing other stuff while it's waiting for the HTTP request to complete. This is so that your browser doesn't just hang in the event it takes a while to load a 500MB file. You can't get `data` because it's being called before the HTTP request has completed, so `response` doesn't contain anything.

`$.getJSON` takes a second argument called a "promise" callback function, which is "promised" to be executed whenever the HTTP request is **complete**. This callback function is always passed an argument that contains the response of the request. So you would want something like this:

```
$.getJSON("http://www.whatever.com", function(responseData){
    //do something with responseData
});
```

**Comment by amaseda** [comment]
@RobertAKARobin Awesome, thanks. Will give this a try after the lab.
